# Generated by Django 4.2 on 2025-05-10 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ceratime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
